services:
  mariadb:
    build:
      context: ./requirements/MariaDB
      dockerfile: Dockerfile
    networks:
      - default
    volumes:
      - ~/data/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - .env

  wordpress:
    build:
      context: ./requirements/Wordpress
      dockerfile: Dockerfile
    volumes:
      - ~/data/wp:/var/www/html
    networks:
      - default
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    dns:
      - 8.8.8.8
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http: //localhost:9000 || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  nginx:
    build:
      context: ./requirements/Nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - default
    depends_on:
      - wordpress
    volumes:
      - ~/data/wp:/var/www/html
    
volumes:
  db_data:

networks:
  default:
    driver: bridge