services:
  mariadb:
    build:
      context: ./requirements/MariaDB
      dockerfile: Dockerfile
    networks:
      - default
    volumes:
      - ~/data/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - .env

  wordpress:
    build:
      context: ./requirements/Wordpress
      dockerfile: Dockerfile
    volumes:
      - ~/data/wp:/var/www/html
    networks:
      - default
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http: //localhost:9000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    

  # nginx:
  #   image: nginx:latest
  #   ports:
  #    - "9000"
    
volumes:
  db_data:

networks:
  default:
    driver: bridge