version: '3.7'

services:
  db:
    image: mariadb:10.4
    container_name: mariadb
    environment:
     MYSQL_ROOT_PASSWORD: 123456
     MYSQL_DATABASE: WP
     MYSQL_USER: lollo
     MYSQL_PASSWORD: 123456
    volumes:
     - ./data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
     - "3306:3306"

  nginx:
    image: nginx:latest
    ports:
     - "9000"
    
volumes:
  db_data:

