version: '3.7'

services:
  db:
    image: mariadb:10.4
    container_name: mariadb
    environment:
     MYSQL_ROOT_PASSWORD: 123456
     MYSQL_DATABASE: WP
     MYSQL_USER: lollo
     MYSQL_PASSWORD: 123456
    ports:
     - "3306:3306"
    

